module.exports = Object.freeze({
    LOWEST_FREQUENCY: 50,
    FREQUENCY_STEP: 10,
    MAX_TIME: 100000,
    LOOT_COEF: 6,
    BOSS_ENEMY_COEF: 5,
    ENEMY_COEF: 1,
    INITIAL_FREQUENCY: 200,
    POINTS_ENEMY_KILLED: 2,
    POINTS_ENEMY_INJURED: 1,
    POINTS_ENEMY_MISSED: -1,
    POINTS_ENEMY_MISSED_RESET: -2,
    POINTS_NOBODY_HIT: -0.5,
    DAMAGE_COEF: 10
});